### PR TITLE
Fix support for void nodes

### LINKED ISSUE #5: "break" nodes not handled and cause a TypeError exception
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: nlcst-to-string >=2.0.4 (at least, maybe older too)

### Steps to reproduce

If there are trailing whitespaces at the end of a line, it seems to get parsed as `type: break` in Markdown, which `nlcst-to-string` doesn't know how to convert to string.

Link to code example: https://codesandbox.io/s/remark-debug-forked-hh0ub?file=/src/index.js

Example AST subtree containing `break`s:

```
[ { type: 'text',
    value: 'Mobile: @6RpN4Ztw3jLwzQtHl8XpnnR58LWZTAjwq2vvfyx7zkc=.ed25519',
    position: 
     { start: { line: 3, column: 1, offset: 53 },
       end: { line: 3, column: 62, offset: 114 },
       indent: [] } },
  { type: 'break',
    position: 
     { start: { line: 3, column: 62, offset: 114 },
       end: { line: 4, column: 1, offset: 117 },
       indent: [ 1 ] } },
  { type: 'text',
    value: 'Desktop: @lOUVT+Phkvai9a/cCS/RKo+S9hnPAQdVixms/7ldpPA=.ed25519',
    position: 
     { start: { line: 4, column: 1, offset: 117 },
       end: { line: 4, column: 63, offset: 179 },
       indent: [] } },
  { type: 'break',
    position: 
     { start: { line: 4, column: 63, offset: 179 },
       end: { line: 5, column: 1, offset: 182 },
       indent: [ 1 ] } },
  { type: 'text',
    value: 'Pub: @5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=.ed25519',
    position: 
     { start: { line: 5, column: 1, offset: 182 },
       end: { line: 5, column: 59, offset: 240 },
       indent: [] } } ]
```

### Expected behavior

No crash or exception thrown in the JS engine. The stringification should complete and `break` nodes should be considered empty string.

### Actual behavior

Uncaught JS exception:

```
[TypeError: Cannot read property 'length' of undefined]
```

### PR DESCRIPTION
**Pull request by staltz**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [ ] If applicable, I’ve added docs and tests

### Description of changes

I tested and deployed this change in https://github.com/staltz/strip-markdown-oneline/commit/347709eeb26729e4a48a883693d2b2f2515e3fbb too

Closes #5

### CODE REVIEW

**Comment by wooorm** [comment]
See https://github.com/syntax-tree/nlcst-to-string/issues/5#issuecomment-831237315.

But if this was causing an exception, then I do think unknown nodes (such as break) should be ignored and handled gracefully

**Comment by staltz** [comment]
Perhaps this PR could be generalized so that nodes that don't have the required fields would be ignored.

**Comment by wooorm** [comment]
Yeah. I think if you do:

```js
children = ('length' in node ? node : node.children) || []
```

on what was L28 that’d work fine?

**Comment by wooorm** [comment]
And a test of the form:

```js
t.equal(toString(u('foo')), '', 'should support voids')
```

**Comment by staltz** [comment]
Good morning @wooorm! I updated this PR according to your suggestions :)

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Good morning André! 🌞 Thanks, released in 3.0.1!

**Pull request merged**
